# -*- coding: utf-8 -*-
"""COVID19_India_Testing_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsDlJLhtiM-W2ZZs64ZIqIbqZgxRLLQw

# 🧪 COVID-19 India: Statewise Testing Analysis

This project analyzes **state-wise COVID-19 testing data** in India using real government-reported figures.

We visualize:
- 📅 Testing trends over time
- 🧪 Tests per state
- 📊 Correlation with confirmed cases
- 🔁 Daily testing growth

---
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

sns.set_style("whitegrid")

"""## 📂 Step 1: Upload Dataset
Upload the file you downloaded from Kaggle or official sources.

"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("StatewiseTestingDetails.csv")
df.head()

"""## 🧹 Step 2: Data Cleaning & Formatting
We’ll convert the date column, check missing values, and standardize state names.

"""

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
df.dropna(inplace=True)
df.columns

"""## 📊 Step 3: Total Tests by State
We’ll calculate the **latest total number of tests per state**.

"""

latest_date = df['Date'].max()
latest_df = df[df['Date'] == latest_date]

top_states = latest_df.groupby('State')['TotalSamples'].max().sort_values(ascending=False).head(10)

plt.figure(figsize=(10, 6))
sns.barplot(x=top_states.values, y=top_states.index, palette="Blues_r")
plt.title(f"Top 10 States by Total COVID-19 Tests as of {latest_date.date()}")
plt.xlabel("Total Samples Tested")
plt.ylabel("State")
plt.show()

"""## 📈 Step 4: Daily Testing Trend for a State
Let’s visualize how testing increased over time for a selected state.

"""

state = "Maharashtra"  # change to any state
state_df = df[df['State'] == state]

plt.figure(figsize=(12, 6))
plt.plot(state_df['Date'], state_df['TotalSamples'], marker='o', color='blue')
plt.title(f"Daily Cumulative Tests in {state}")
plt.xlabel("Date")
plt.ylabel("Total Samples Tested")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## 🔁 Step 5: Daily Testing Growth Rate (Optional)
We calculate day-to-day increase in tests for deeper insights.

"""

state_df['DailyIncrease'] = state_df['TotalSamples'].diff()

plt.figure(figsize=(12, 5))
plt.bar(state_df['Date'], state_df['DailyIncrease'], color='orange')
plt.title(f"Daily New Tests in {state}")
plt.xlabel("Date")
plt.ylabel("Tests Per Day")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## ✅ Conclusion

In this project, we:
- Uploaded statewise testing data
- Visualized top testing states
- Tracked testing growth over time
- Analyzed daily increases and trends

📈 This data helps understand how aggressively different states have tested during the pandemic.

"""